### ISSUE TITLE
Basic Frontend

### ISSUE THREAD

**Issue by KAIYOHUGO** [mdcpp/mdoj#16]
# TODO

- [x] Navbar
- [x] Footer
- [x] Login page
- [x] web-grpc api config 
- [x] fix ssr error
- [x] Use cookie for token to complete fix ssr error
- [ ] Error handling (Modal)
- [ ] Problems page
- [ ] Search bar
- [ ] Contests page
- [ ] Rank page
- [ ] Submission page
- [ ] About Page
- [ ] Admin page
- [ ] session managment

**Comment by KAIYOHUGO** [comment]
Some Note, you can add this in workspace `.vscode/setting.json` to improve devexp. need in workspace root because ra don't read the .vscode config file in member folder

```json
{
    "rust-analyzer.cargo.features": "all",
    "rust-analyzer.rustfmt.overrideCommand": [
        "leptosfmt",
        "--stdin",
        "--rustfmt"
    ],
    "emmet.includeLanguages": {
        "rust": "html"
    }
}
```
